#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PazhHesabdari
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB")]
	public partial class dblinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_user(tb_user instance);
    partial void Updatetb_user(tb_user instance);
    partial void Deletetb_user(tb_user instance);
    #endregion
		
		public dblinqDataContext() : 
				base(global::PazhHesabdari.Properties.Settings.Default.DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dblinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_user> tb_users
		{
			get
			{
				return this.GetTable<tb_user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_users")]
	public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_fname;
		
		private string _user_lname;
		
		private string _username;
		
		private string _password;
		
		private string _user_date_add;
		
		private System.Nullable<bool> _user_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_fnameChanging(string value);
    partial void Onuser_fnameChanged();
    partial void Onuser_lnameChanging(string value);
    partial void Onuser_lnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onuser_date_addChanging(string value);
    partial void Onuser_date_addChanged();
    partial void Onuser_statusChanging(System.Nullable<bool> value);
    partial void Onuser_statusChanged();
    #endregion
		
		public tb_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_fname", DbType="NVarChar(50)")]
		public string user_fname
		{
			get
			{
				return this._user_fname;
			}
			set
			{
				if ((this._user_fname != value))
				{
					this.Onuser_fnameChanging(value);
					this.SendPropertyChanging();
					this._user_fname = value;
					this.SendPropertyChanged("user_fname");
					this.Onuser_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_lname", DbType="NVarChar(50)")]
		public string user_lname
		{
			get
			{
				return this._user_lname;
			}
			set
			{
				if ((this._user_lname != value))
				{
					this.Onuser_lnameChanging(value);
					this.SendPropertyChanging();
					this._user_lname = value;
					this.SendPropertyChanged("user_lname");
					this.Onuser_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_date_add", DbType="NVarChar(50)")]
		public string user_date_add
		{
			get
			{
				return this._user_date_add;
			}
			set
			{
				if ((this._user_date_add != value))
				{
					this.Onuser_date_addChanging(value);
					this.SendPropertyChanging();
					this._user_date_add = value;
					this.SendPropertyChanged("user_date_add");
					this.Onuser_date_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_status", DbType="Bit")]
		public System.Nullable<bool> user_status
		{
			get
			{
				return this._user_status;
			}
			set
			{
				if ((this._user_status != value))
				{
					this.Onuser_statusChanging(value);
					this.SendPropertyChanging();
					this._user_status = value;
					this.SendPropertyChanged("user_status");
					this.Onuser_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
